# ========== Pull Requests ===========
-
  version: 1.0.0-{branch}-{build}

  assembly_info:
    patch: true
    file: "VersionInfo.cs"
    assembly_version: "1.0.0"
    assembly_file_version: "1.0.0.{build}"
    assembly_informational_version: "1.0.0-alpha{build}"

  configuration: Release
  platform: Any CPU
  before_build:
    - nuget restore
  build:
    include_nuget_references: false
    publish_nuget: true
    publish_nuget_symbols: false
